### ISSUE TITLE
Removing formats doesn't seem to work

### ISSUE THREAD

**Issue by FatOrangutan** [piroor/copy-selected-tabs-to-clipboard#1]
v1.0.2 on Nightly 65.0a1 (2018-11-12)

Steps:
1. Click the `x` on a row in the format table.
2. Select multiple tabs, right click them, `Copy to Clipboard >`. Row that you removed in the previous step is still visible. Browser Console says `TypeError: row.parentNode is null; can't access its "childNodes" property init.js:237:3`

![capture](https://user-images.githubusercontent.com/8336638/48387737-02181280-e71d-11e8-9610-069fd54276e5.PNG)

**Comment by piroor** [comment]
Thanks! This has been fixed by recent commits.
