### ISSUE TITLE
Feature request: simplify URL's

### ISSUE THREAD

**Issue by joshgold22** [piroor/copy-selected-tabs-to-clipboard#11]
## Short description

Either or both of the following would be helpful, but especially the first:

1. (simple) Add a new placeholder for %URL_SIMPLE% (or perhaps a better name) that copies the URL stripped of everything after the first ?.

(e.g., given https://www.nytimes.com/interactive/2020/05/19/burst/compost-box-indoors-coronavirus.html?action=click&module=Top%20Stories&pgtype=Homepage&contentCollection=AtHome&package_index=0 copies https://www.nytimes.com/interactive/2020/05/19/burst/compost-box-indoors-coronavirus.html )

* It would be best to include a domain whitelist (or even perhaps a domain+parameter whitelist) where some could be kept.  e.g., the Google ?q parameter is one I'd imagine keeping.

2. (more flexible and could be designed in various ways) Add a separate preference to allow regular expression replacement in URLs, or some other kinds of modifications (similar to the Neat URL or Lean URL firefox addons)

To comment on priority, I would find 1 most helpful (and certainly most worthwhile versus the  effort!)  I would also find 1. helpful even if 2. is provided:  Sometimes I'd want to strip arguments no matter the domain; and having 1. allows the user to decide how it will be copied when they choose a format from the menu.

**Comment by piroor** [comment]
OK, now `%REPLACE(...)%` is supported. It takes one base text and one or more matcher/replaced-text pairs, like: `%REPlACE("base text", "matcher regexp 1", "replaced 1", "matcher regexp 2", "replaced 2", ...)%`

**Comment by piroor** [comment]
The matcher part is treated as a JavaScript regular expression, case-insensitive and not global match. So, you can define exception domains with a [negative lookahead](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Assertions#Other_assertions). For example:
`%REPLACE("%URL%", "^((?!\w+://([^/]*\.)?(google\.com|duckduckgo\.com)/.*).*)\?.*$", "$1")% `

**Comment by piroor** [comment]
The automated test may help you to understand detailed specs of the `%REPLACE(...)%` feature:
https://github.com/piroor/copy-selected-tabs-to-clipboard/blob/7a57efcb6b2074d2e5c0bbb6fcc0717ef5587fee/test/test-replacer.js
