### ISSUE TITLE
%DESCRIPTION% not working

### ISSUE THREAD

**Issue by DavidMcRitchie** [piroor/copy-selected-tabs-to-clipboard#12]
## Short description
Was failing with error codes  now have a mixture of returning nothing or  error codes

## Steps to reproduce

Test1 %URL%  

https://mail.aol.com/webmail-std/en-us/suite
https://github.com/piroor/copy-selected-tabs-to-clipboard/labels
view-source:https://github.com/piroor/copy-selected-tabs-to-clipboard/labels
about:addons

Test2 %description%123%DESCRIPTION%345%TITLE%678%EOF% 

123345AOL Mail (5333)678%EOF%
123345Issues · piroor/copy-selected-tabs-to-clipboard · GitHub678%EOF%
123345https://github.com/piroor/copy-selected-tabs-to-clipboard/labels678%EOF%
123345Add-ons Manager678%EOF%\

HTML Link with Description
<a href="%URL_HTML%" title="%DESCRIPTION%">%TITLE_HTML%</a>

and added another  tab and retested
http://dmcritchie.mvps.org/dolphin/lesson_from_newtab.htm   

params.tab is undefined
fillPlaceHoldersInternal@moz-extension://c8319d8c-7857-437d-aa04-f6621a670f5b/common/commands.js:221:1
fillPlaceHolders@moz-extension://c8319d8c-7857-437d-aa04-f6621a670f5b/common/commands.js:188:44

<a href="https://github.com/piroor/copy-selected-tabs-to-clipboard/labels" title="">Issues · piroor/copy-selected-tabs-to-clipboard · GitHub</a>
<a href="view-source:https://github.com/piroor/copy-selected-tabs-to-clipboard/labels" title="">https://github.com/piroor/copy-selected-tabs-to-clipboard/labels</a>
<a href="about:addons" title="">Add-ons Manager</a>
params.tab is undefined
fillPlaceHoldersInternal@moz-extension://c8319d8c-7857-437d-aa04-f6621a670f5b/common/commands.js:221:1
fillPlaceHolders@moz-extension://c8319d8c-7857-437d-aa04-f6621a670f5b/common/commands.js:188:44

 

## Expected result
A good link  to go into an HTML file or to paste  into an RTF document

<a href="http://dmcritchie.mvps.org/dolphin/lesson_from_newtab.htm" Title="Interactive tutorial to show some of the things that can be done with bookmarklets in a browser, some features of the Chrome browser, and a collection of the extensions I am using in Chrome.">Bookmarklets, history, exported bookmarks, extensions for Chrome (2020-07-25)</a>

## Actual result
Results shown above

## Environment

 * Platform (OS):  Windows 10    on ASUS T100TA
 * Version of Firefox:  78.0.2
 *Version of Copy Selected Tabs to Clipboard:  1.3.0
 * Version (or revision) of Multiple Tab Handler:  didn't see requirement for MTH (not installed), 
  Enabled  3.1.3

Results still the same)

params.tab is undefined
fillPlaceHoldersInternal@moz-extension://c8319d8c-7857-437d-aa04-f6621a670f5b/common/commands.js:221:1
fillPlaceHolders@moz-extension://c8319d8c-7857-437d-aa04-f6621a670f5b/common/commands.js:188:44

params.tab is undefined
fillPlaceHoldersInternal@moz-extension://c8319d8c-7857-437d-aa04-f6621a670f5b/common/commands.js:221:1
fillPlaceHolders@moz-extension://c8319d8c-7857-437d-aa04-f6621a670f5b/common/commands.js:188:44

<a href="view-source:https://github.com/piroor/copy-selected-tabs-to-clipboard/labels" title="">https://github.com/piroor/copy-selected-tabs-to-clipboard/labels</a>
<a href="about:addons" title="">Add-ons Manager</a>
params.tab is undefined
fillPlaceHoldersInternal@moz-extension://c8319d8c-7857-437d-aa04-f6621a670f5b/common/commands.js:221:1
fillPlaceHolders@moz-extension://c8319d8c-7857-437d-aa04-f6621a670f5b/common/commands.js:188:44

**Comment by piroor** [comment]
Thanks! The commit df63426 should fix this.

**Comment by DavidMcRitchie** [comment]
Thanks Piro, just came back to try to make the pattern show up better and it is already solved/closed.

Love the tools for keeping track of changes in github (like archive.org, and wikipedia.org), and the fix shows me how shortened words are official as the examples didn't exactly match definitions.   

The whole process is a lot better than using email or newsgroup as we had done before.
