### ISSUE TITLE
Attributes in alphabetical not in order presented in pattern 

### ISSUE THREAD

**Issue by DavidMcRitchie** [piroor/copy-selected-tabs-to-clipboard#13]
## Short description
href  attribute tags are being generated in alphabetcal ordet rather than order specified

## Steps to reproduce
Using    ^  instead of  <   so page does not get messed  up.

HTML Link with Desc ^LI>
^li>^a target="_blank" href="%URL_HTML%" title="%DESCRIPTION_HTML%">%TITLE_HTML%^/a>^/li>%RT%
. 

attribute tags came out in alphabetical order within Anchor element
   href=   target=    title=
instead of the order presented
   target=  href=    title=

## Expected result
expected them in the order I presented

## Why this is  important to me
I enter a lot of links manually and type the href="h... immediately after the A.
I want to change  links later to insert target="_blank" immediately after the A.
* But not if  target="_blank" has already been  inserted.
* and not if  it the link  is on the same page
* and not if  the link is a bookmarklet   ^a href="javascript:...

change all      '^a href="h'     to    '^a target="_blank" href="h'

## Environment

 * Platform (OS):   Window10
 * Version of Firefox: 79.0
 * Version of Copy Selected Tabs to Clipboard is 1.3.1

##Other
Thanks for fixing Description #12  it is active

**Comment by piroor** [comment]
FYI: you can put HTML sources as is with "preformattted" text mark:

```html
<li><a target="_blank" href="%URL_HTML%" title="%DESCRIPTION_HTML%">%TITLE_HTML%</a></li>%RT%
```

**Comment by DavidMcRitchie** [comment]
I tried yours, then I tried mine, both had the same output, exactly what I wanted and expected.Then I checked the version still 1.3.1
Close it as user error, I can't see how I saw something completely different earlier today.Sorry to bother you, embarrassing for me.   The output looks great.

**Comment by piroor** [comment]
Ah, sorry for a confusable comment. I actually just wrote about a syntax on this issue tracker. I've not researched about the problem you reported yet...

**Comment by piroor** [comment]
I've tried to reproduce but I couldn't.

This addon fills the placeholders at https://github.com/piroor/copy-selected-tabs-to-clipboard/blob/486db22d70fd887fbb4eed19cffb045b68bc4a42/common/commands.js#L189 and the operation will be done based on simple string replacement. The logic doesn't parse HTML so attributes won't be rearranged by this addon. I prepared some tabs and select-and-copy, then I pasted it to some applications:

* Notepad2
* Wordpad
* This textarea

But I successfully got HTML sources same as the definition.

On the other hand, when you paste the data to any application like Microsoft Word, LibreOffice Writer, Google Docs, or any other application with rich-text support, the pasted data will be parsed by the receiver application. And if you get the HTML source on the application, attributes may be sorted by the application itself.

Could you describe more detailed steps to reproduce? Which application do you use, and how to get the HTML source on the application?

**Comment by DavidMcRitchie** [comment]
Found the problem,as you suggested some things might rearrange the code.     
https://bestonlinehtmleditor.com/    did rearrange the code
When pasted into code is exactly what I wanted with target=    first.
When pasted in as RTF and then look at the code this is what I saw. It does generate the ul  and  /ul  when pasted as RTF

Don't know if this is going to look like HTML code or not,  but is the problem as described.

<pre><ul>
    <li><a href="https://bestonlinehtmleditor.com/" target="_blank" title="Free web based html editor for you to use to edit html easily on your website, in your shopping cart or anywhere else you use html.">BEST ONLINE HTML EDITOR | Best Free Online WYSIWYG HTML Editor</a></li>
</ul>
</pre>

Of course I would not be going thru this to add to a webpage.This was test it output was correct.    Into notepad code is as expected 

I  was testing with a different HTML editor yesterday and did not see the problem, this one has more features.
So was already determined  yesterday your stuff  is good and not a problem.And today that I am not insane, which is a relief.   Just not a good tester..

 
 
 
-----Original Message-----

**Comment by DavidMcRitchie** [comment]
Was looking  at output in an HTML editor after switching between the two views, not a problem with this addon.
