### ISSUE TITLE
Add "Copy This Tree" command for TST

### ISSUE THREAD

**Issue by piroor** [piroor/copy-selected-tabs-to-clipboard#16]
https://github.com/piroor/treestyletab/issues/2747

Commands:

* Copy This Tree (middle click should copy descendants) 
* Copy Descendants (middle-click should copy the tree)

Context:

* Activate them when TST is installed and the context tab is a tree.
* Deactivate them when TST is not installed.

**Comment by piroor** [comment]
Done with recent commits.

**Comment by cweagans** [comment]
You're a gentleman and a scholar. My Firefox experience wouldn't be half as enjoyable without your work. Thank you!!

**Comment by piroor** [comment]
I've released 1.4.0 with this improvement. Please try it!

**Comment by cweagans** [comment]
Works like a charm! Thanks again!!
