### ISSUE TITLE
Option to hide context menu items from page context menu

### ISSUE THREAD

**Issue by Lej77** [piroor/copy-selected-tabs-to-clipboard#2]
## Short description
I would like an option to not show context menu items when a webpage is right clicked. I only want to use the context menu items by right clicking on a tab.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install Copy Selected Tabs to Clipboard.
 3. Right click anywhere on a webpage.

## Expected result
The context menu shouldn't have a `Copy to Clipboard` item.

## Actual result
The context menu has a `Copy to Clipboard` item.

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 64.0
 * Version (or revision) of Copy Selected Tabs to Clipboard: 1.0.4

**Comment by piroor** [comment]
Thanks. I've add ability to set visibility of context menu items by recent commits.

**Comment by Lej77** [comment]
Thanks!
