### ISSUE TITLE
I want to change the newline code.

### ISSUE THREAD

**Issue by tomokaz1024** [piroor/copy-selected-tabs-to-clipboard#34]
## Short description
I want to change the newline code.
## Steps to reproduce

 1. Selecting Multiple Tabs
 2. Copying to the clipboard

## Expected result
Newline code is lf.

## Actual result
Newline code is cr+lf.

## Environmenthttps://docs.github.com/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax

 * Platform (OS):  Windows10
 * Version of Firefox: 103.0.2
 * Version (or revision) of Multiple Tab Handler: 1.4.5

**Comment by piroor** [comment]
Options of this addon => Development => check "Debug mode" => All Configs => uncheck "useCRLF" should produce the expected result. Could you try it?

Hmm, but it is mysterious. It is unchecked by default...

**Comment by tomokaz1024** [comment]
I could change the newline code. 
Thanks.
