### ISSUE TITLE
New format added with each keypress!

### ISSUE THREAD

**Issue by deant** [piroor/copy-selected-tabs-to-clipboard#4]
I tried adding a new format, called "URL|Title".
Then, thinking that the "|" character might be triggering some kind of special behavior, I edited that to "URI and Title (for YTDL)".  When that didn't help, I switched back to "URI|Title"
As you can see in the image below, each character entered seems to have created a new format entry in the context menu!

Also, my desired order of context menu items isn't respected:  The custom ones are all at the bottom.

I'd note that clicking the "URI|Title" option does indeed work correctly, so this bug is just related to (many!) extra items and incorrect ordering in the context menu.

I'm using v1.0.7 (2019.8.8) on Firefox 69.0 x64, Windows 10 x64 v1809 (Build 17763.737)

Screenshot:

![screenshot](https://user-images.githubusercontent.com/4946606/65121686-009d3200-da33-11e9-8957-7ec06afeccb9.png)

**Comment by piroor** [comment]
Hmm, this is reproduced on my environment also and the broken context menu looks fixed after reloading of the addon (disabling and re-enabling via the addons manager). This looks a problem around operations to apply updated configs dynamically.

**Comment by piroor** [comment]
OK, I got it. The commit 21333da should fix both problems: too much garbage and unchangeable order of items.

**Comment by deant** [comment]
Great!  And super-fast response, too.

So, I guess I just wait and the addon will update on its own once you publish the updated version?

**Comment by piroor** [comment]
A new version 1.0.8 is already released so it will be downloaded automatically.
