### ISSUE TITLE
Offer multiple copy modes/selects

### ISSUE THREAD

**Issue by rixx** [piroor/copy-selected-tabs-to-clipboard#43]
## Short description

Currently, you have to select what happens on click and on middle click when copying tabs. But sometimes, I want to copy a full tree, sometimes just descendants (which is a great feature, especially with the proper indentation!) and sometimes just the single tab.

Couldn't it be possible to make each of these an entry in the context menu? So that I could just straight up select the context menu for "copy this tab" or "copy descendants" without having to remember which was right-click, middle-click etc.

**Comment by piroor** [comment]
It is "possible" but I have a concern about its actual usability. WebExtensions API based addons can provide only one top level context menu item. If I introduce two top level commands like "Copy this tab" and "Copy descendants", you'll see deeply nested menu like:

* New Tab
* Reload Tab
* ...
* Close Tab
* Close Multiple Tabs
* Copy Selected Tabs to Clipboard (top level item)
  * Copy this tab
    * format 1
    * format 2
    * format 3
  * Copy descendants
    * format 1
    * format 2
    * format 3

Another idea, "copy this tab" and "copy descendants" submenu items under each "format" item may help your demand. This idea may effective if addons can track clicking on an upper level item. I'll try that.

**Comment by rixx** [comment]
Oh yeah, that does sound annoying. Your suggestion sounds much more sensible, thank you!

**Comment by piroor** [comment]
Hmm, I've tried an experimental branch and sadly my idea does not work actually...

![image](https://github.com/piroor/copy-selected-tabs-to-clipboard/assets/70062/4bbdfb87-91eb-46e5-8841-176b95f6d3b1)

I think it is annoying also . How do you think about hat?

**Comment by rixx** [comment]
I do like having the choice, but if I am a minority / if you think it is annoying, I can also close this issue. Definitely understand why it's tricky, UI-wise.

**Comment by piroor** [comment]
![image](https://github.com/piroor/copy-selected-tabs-to-clipboard/assets/70062/bb643136-f493-426e-a268-da789ce4b47a)
OK, finally I've implemented this feature as an optional behavior. The submenu is available with the choice "Choose from menu always".
