### ISSUE TITLE
Regression: v1.6.0 breaks "Show context menu item in the context menu on the content area" option

### ISSUE THREAD

**Issue by Gitoffthelawn** [piroor/copy-selected-tabs-to-clipboard#48]
## Short description
Regression: v1.6.0 breaks "Show context menu item in the context menu on the content area" option

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install CSTTC.
 3. In CSTTC's options, deselect the "Show context menu item in the context menu on the content area" option.
 4. In CSTTC's options, deselect all checkboxes - except the first checkbox - in the section below the `Separator of copied items` section.
 5. Open any web page.
 6. Right click on an empty content area.
 7. Notice that the CSTTC context menu appears.

## Expected result
No CSTTC context menu in content area.

## Actual result
CSTTC context menu in content area.

## Environment

 * Platform (OS): Linux
 * Version of Firefox: 115ESR
 * Version (or revision) of CSTTC: v1.6.0

**Comment by piroor** [comment]
This couldn't be reproduced on Firefox ESR115 on Windows. Could you paste full options of this addon?

**Comment by Gitoffthelawn** [comment]
@piroor  I apologize.  I left out a step.  Please see the edited STR, specifically step 4, which I added.

**Comment by piroor** [comment]
Thanks! I've confirmed that the item "copy to clipboard: URL" (on my case) appears on the content area regardless the second checkbox is unchecked.

**Comment by Gitoffthelawn** [comment]
@piroor You're welcome. No rush... just curious... what's your guesstimated time to release a fix?  If it's going to be a bit, I'll just add a line of code to `userChrome.css`.  If you're planning to release a fix soon, I won't bother. :)

**Comment by piroor** [comment]
I've released 1.6.1 with this fix. Please try it after it is granted and published.

**Comment by Gitoffthelawn** [comment]
v1.6.1 fixes this issue.  Thank you!
