### ISSUE TITLE
[Feature Request] Don't use a submenu if only one format is enabled

### ISSUE THREAD

**Issue by FatOrangutan** [piroor/copy-selected-tabs-to-clipboard#7]
## Short description
It would be great if the submenu could be avoided if only one format is enabled in the Options page, so that the actionable menuitem can be present in the root menu itself.

## Steps to reproduce

 1. Start Firefox with a clean profile.
 2. Install the add-on.
 3. Go to its Options and remove all but one formats

## Expected result
There is only one format enabled, hence it shouldn't be behind a submenu.

## Actual result
It is behind a submenu.

![Capture](https://user-images.githubusercontent.com/8336638/76885863-efc85e80-68a5-11ea-9253-cc1ea98a9be7.PNG)

## Environment

 * Platform (OS): Windows 10 
 * Version of Firefox: Nightly
 * Version (or revision) of Copy Selected Tabs to Clipboard: v1.0.9

**Comment by piroor** [comment]
I've implemented this together with #8. Thanks again!

**Comment by FatOrangutan** [comment]
Thanks a lot! One little issue I noticed: it seems that this menuitem doesn't respect the 'Show context menu item in the context menu on the content area' setting. So STR:

1) In the Options page, uncheck all but one formats
2) Uncheck 'Show context menu item in the context menu on the content area'
3) Click empty area on some page

AR: 
![Capture](https://user-images.githubusercontent.com/8336638/77004942-f1695380-6985-11ea-8ba7-94cd89dabc57.PNG)

**Comment by piroor** [comment]
Thanks! The regression has been fixed with the commit a641d04.
