### ISSUE TITLE
[Feature Request] Check/uncheck desired formats instead of removing and (re-)adding them

### ISSUE THREAD

**Issue by FatOrangutan** [piroor/copy-selected-tabs-to-clipboard#8]
Desired use case: Stick to a set of formats that you use frequently. Occasionally, enable some extra formats when needed. Disable these formats when not needed to keep the menu small.

Currently, this requires:

1. Set up your desired formats, removing the ones that you don't need.
2. When the need arises, add the extra formats you need.
3. When you no longer need those formats, remove them.
4. Repeat step 2 when needed.

![current](https://user-images.githubusercontent.com/8336638/76888056-3d929600-68a9-11ea-85c9-de80e549c4ab.PNG)

I would prefer:

1. Set up your desired formats, unchecking the ones that you don't need.
2. When the need arises, simply 'check' the formats you need.
3. When you no longer need those formats, simply 'uncheck' them.
4. Repeat step 2 when needed.

![desired](https://user-images.githubusercontent.com/8336638/76888140-67e45380-68a9-11ea-8ea4-c89081270c9c.PNG)

## Environment

 * Platform (OS): Windows
 * Version of Firefox: Nightly
 * Version (or revision) of Copy Selected Tabs to Clipboard: 1.0.9

**Comment by piroor** [comment]
Thanks, this sounds good! I've implemented this with recent commits.
