### ISSUE TITLE
Feature request: keyboard shortcuts

### ISSUE THREAD

**Issue by joshgold22** [piroor/copy-selected-tabs-to-clipboard#9]
I'd like to be able to specify keyboard shortcuts to copy the selected tabs.  (Including for custom formats.)

 * Platform (OS):  OSX
 * Version of Firefox:  75
 * Version (or revision) of Multiple Tab Handler: 3.1.2

**Comment by piroor** [comment]
Thank you for a suggestion. I've implemented ability to set custom shortcuts for each format:

![image](https://user-images.githubusercontent.com/70062/79953893-898fb680-84b7-11ea-91ea-c5382b672e43.png)

Moreover you can set an accesskey for each format with the mark '&'.

![image](https://user-images.githubusercontent.com/70062/79954135-db384100-84b7-11ea-8424-5eb2df23a1d8.png)
